import { cva, type VariantProps } from "class-variance-authority";

export const buttonVariants = cva(
  [
    "relative inline-flex items-center justify-center rounded-xl",
    "font-bold tracking-wide transition-all duration-150 ease-out",
    "px-6 py-3 text-base",
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2",
    "disabled:opacity-60 disabled:cursor-not-allowed disabled:shadow-none",
    "disabled:hover:transform-none disabled:active:transform-none",
    "disabled:hover:shadow-none disabled:active:shadow-none",
    "active:translate-y-1 active:shadow-none",
    "border-2 border-b-4",
    "dark:focus-visible:ring-offset-gray-800",
  ],
  {
    variants: {
      variant: {
        primary: [
          "bg-green-500 border-green-700",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#15803d]",
          "hover:bg-green-400 hover:border-green-600",
          "hover:shadow-[0_6px_0_#15803d] hover:-translate-y-0.5",
          "focus-visible:ring-green-400",
          "dark:bg-green-600 dark:border-green-800",
          "dark:shadow-[0_4px_0_#15803d]",
          "dark:hover:bg-green-500 dark:hover:border-green-700",
        ],
        secondary: [
          "bg-green-50 border-green-200",
          "text-green-800 font-extrabold",
          "shadow-[0_4px_0_#bbf7d0]",
          "hover:bg-green-100 hover:border-green-300",
          "hover:shadow-[0_6px_0_#86efac] hover:-translate-y-0.5",
          "focus-visible:ring-green-300",
          "dark:bg-gray-800 dark:border-gray-600",
          "dark:text-green-400 dark:shadow-[0_4px_0_#374151]",
          "dark:hover:bg-gray-700 dark:hover:border-gray-500",
        ],
        success: [
          "bg-emerald-500 border-emerald-700",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#047857]",
          "hover:bg-emerald-400 hover:border-emerald-600",
          "hover:shadow-[0_6px_0_#047857] hover:-translate-y-0.5",
          "focus-visible:ring-emerald-400",
          "dark:bg-emerald-600 dark:border-emerald-800",
          "dark:shadow-[0_4px_0_#047857]",
          "dark:hover:bg-emerald-500 dark:hover:border-emerald-700",
        ],
        error: [
          "bg-red-500 border-red-700",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#b91c1c]",
          "hover:bg-red-400 hover:border-red-600",
          "hover:shadow-[0_6px_0_#b91c1c] hover:-translate-y-0.5",
          "focus-visible:ring-red-400",
          "dark:bg-red-600 dark:border-red-800",
          "dark:shadow-[0_4px_0_#b91c1c]",
          "dark:hover:bg-red-500 dark:hover:border-red-700",
        ],
        danger: [
          "bg-red-500 border-red-700",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#b91c1c]",
          "hover:bg-red-400 hover:border-red-600",
          "hover:shadow-[0_6px_0_#b91c1c] hover:-translate-y-0.5",
          "focus-visible:ring-red-400",
          "dark:bg-red-600 dark:border-red-800",
          "dark:shadow-[0_4px_0_#b91c1c]",
          "dark:hover:bg-red-500 dark:hover:border-red-700",
        ],
        warning: [
          "bg-yellow-400 border-yellow-600",
          "text-yellow-900 font-extrabold",
          "shadow-[0_4px_0_#ca8a04]",
          "hover:bg-yellow-300 hover:border-yellow-500",
          "hover:shadow-[0_6px_0_#ca8a04] hover:-translate-y-0.5",
          "focus-visible:ring-yellow-400",
          "dark:bg-yellow-600 dark:border-yellow-800",
          "dark:text-white dark:shadow-[0_4px_0_#ca8a04]",
          "dark:hover:bg-yellow-500 dark:hover:border-yellow-700",
        ],
        info: [
          "bg-blue-500 border-blue-700",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#1d4ed8]",
          "hover:bg-blue-400 hover:border-blue-600",
          "hover:shadow-[0_6px_0_#1d4ed8] hover:-translate-y-0.5",
          "focus-visible:ring-blue-400",
          "dark:bg-blue-600 dark:border-blue-800",
          "dark:shadow-[0_4px_0_#1d4ed8]",
          "dark:hover:bg-blue-500 dark:hover:border-blue-700",
        ],
        ghost: [
          "bg-transparent border-transparent shadow-none",
          "text-gray-700 font-bold",
          "hover:bg-gray-100 hover:text-gray-800",
          "focus-visible:ring-gray-300",
          "dark:text-gray-200",
          "dark:hover:bg-gray-700 dark:hover:text-gray-100",
          "dark:focus-visible:ring-gray-500",
        ],
        outline: [
          "bg-white border-gray-300",
          "text-gray-800 font-bold",
          "shadow-[0_4px_0_#d1d5db]",
          "hover:bg-gray-50 hover:border-gray-400",
          "hover:shadow-[0_6px_0_#9ca3af] hover:-translate-y-0.5",
          "focus-visible:ring-gray-400",
          "dark:bg-gray-900 dark:border-gray-700",
          "dark:text-gray-100",
          "dark:hover:bg-gray-800 dark:hover:border-gray-600",
          "dark:focus-visible:ring-gray-600",
        ],
        subtle: [
          "bg-gray-100 border-gray-200",
          "text-gray-700 font-semibold",
          "hover:bg-gray-200 hover:text-gray-900",
          "focus-visible:ring-gray-200",
          "dark:bg-gray-800 dark:border-gray-700",
          "dark:text-gray-200",
          "dark:hover:bg-gray-700 dark:hover:text-gray-50",
        ],
        elevation: [
          "bg-white border-transparent shadow-xl",
          "text-gray-900 font-bold",
          "hover:shadow-[0_22px_40px_rgba(15,23,42,0.18)] hover:-translate-y-0.5",
          "hover:bg-gray-50",
          "focus-visible:ring-blue-200",
          "dark:bg-gray-900 dark:text-white",
          "dark:hover:bg-gray-800",
        ],
        // Legacy variants
        sidebar: [
          "bg-white border-slate-300 shadow-[0_4px_0_#cbd5e1]",
          "text-slate-500 font-bold",
          "hover:bg-slate-50 hover:text-slate-600",
          "hover:shadow-[0_6px_0_#cbd5e1] hover:-translate-y-0.5",
          "focus-visible:ring-slate-300",
        ],
        sidebarOutline: [
          "bg-white border-slate-300 shadow-[0_4px_0_#cbd5e1]",
          "text-blue-500 font-bold",
          "hover:bg-slate-50 hover:text-blue-600",
          "hover:shadow-[0_6px_0_#cbd5e1] hover:-translate-y-0.5",
          "focus-visible:ring-blue-400",
        ],
        link: [
          "bg-transparent border-transparent shadow-none p-0 h-auto",
          "text-blue-600 font-semibold underline-offset-4",
          "hover:text-blue-500 hover:underline",
          "focus-visible:ring-offset-0 focus-visible:ring-blue-500",
          "dark:text-blue-400 dark:hover:text-blue-300",
          "dark:focus-visible:ring-blue-400",
        ],
        ai: [
          "border border-transparent bg-transparent",
          "text-purple-600 dark:text-purple-200 font-semibold",
          "overflow-hidden",
          "before:absolute before:inset-0 before:rounded-xl before:content-['']",
          "before:bg-[conic-gradient(from_0deg,#8b5cf6,#6366f1,#ec4899,#f97316,#14b8a6,#8b5cf6)]",
          "before:opacity-80 before:animate-[spin_6s_linear_infinite]",
          "after:absolute after:inset-[2px] after:rounded-lg after:content-['']",
          "after:bg-white dark:after:bg-gray-900",
          "hover:-translate-y-0.5 hover:before:opacity-100",
          "focus-visible:ring-purple-400 focus-visible:ring-offset-2",
          "shadow-none",
        ],
        compute: [
          "bg-orange-600 border-orange-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#c2410c]",
          "hover:bg-orange-500 hover:border-orange-700",
          "hover:shadow-[0_6px_0_#c2410c] hover:-translate-y-0.5",
          "focus-visible:ring-orange-400",
          "dark:bg-orange-700 dark:border-orange-900",
          "dark:shadow-[0_4px_0_#c2410c]",
          "dark:hover:bg-orange-600 dark:hover:border-orange-800",
        ],
        storage: [
          "bg-blue-600 border-blue-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#1e40af]",
          "hover:bg-blue-500 hover:border-blue-700",
          "hover:shadow-[0_6px_0_#1e40af] hover:-translate-y-0.5",
          "focus-visible:ring-blue-400",
          "dark:bg-blue-700 dark:border-blue-900",
          "dark:shadow-[0_4px_0_#1e40af]",
          "dark:hover:bg-blue-600 dark:hover:border-blue-800",
        ],
        security: [
          "bg-purple-600 border-purple-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#7c3aed]",
          "hover:bg-purple-500 hover:border-purple-700",
          "hover:shadow-[0_6px_0_#7c3aed] hover:-translate-y-0.5",
          "focus-visible:ring-purple-400",
          "dark:bg-purple-700 dark:border-purple-900",
          "dark:shadow-[0_4px_0_#7c3aed]",
          "dark:hover:bg-purple-600 dark:hover:border-purple-800",
        ],
        networking: [
          "bg-teal-600 border-teal-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#0f766e]",
          "hover:bg-teal-500 hover:border-teal-700",
          "hover:shadow-[0_6px_0_#0f766e] hover:-translate-y-0.5",
          "focus-visible:ring-teal-400",
          "dark:bg-teal-700 dark:border-teal-900",
          "dark:shadow-[0_4px_0_#0f766e]",
          "dark:hover:bg-teal-600 dark:hover:border-teal-800",
        ],
        management: [
          "bg-emerald-600 border-emerald-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#047857]",
          "hover:bg-emerald-500 hover:border-emerald-700",
          "hover:shadow-[0_6px_0_#047857] hover:-translate-y-0.5",
          "focus-visible:ring-emerald-400",
          "dark:bg-emerald-700 dark:border-emerald-900",
          "dark:shadow-[0_4px_0_#047857]",
          "dark:hover:bg-emerald-600 dark:hover:border-emerald-800",
        ],
        aiml: [
          "bg-violet-600 border-violet-800",
          "text-white font-extrabold",
          "shadow-[0_4px_0_#7c3aed]",
          "hover:bg-violet-500 hover:border-violet-700",
          "hover:shadow-[0_6px_0_#7c3aed] hover:-translate-y-0.5",
          "focus-visible:ring-violet-400",
          "dark:bg-violet-700 dark:border-violet-900",
          "dark:shadow-[0_4px_0_#7c3aed]",
          "dark:hover:bg-violet-600 dark:hover:border-violet-800",
        ],
      },
      size: {
        xs: "h-8 px-2 text-xs min-w-[80px]",
        sm: "h-9 px-4 text-sm min-w-[100px]",
        md: "h-11 px-6 text-base min-w-[120px]",
        lg: "h-12 px-8 text-lg min-w-[140px]",
        xl: "h-14 px-8 text-xl min-w-[160px]",
        icon: "h-11 w-11 p-0 min-w-[44px]",
      },
      fullWidth: {
        true: "w-full",
        false: "",
      },
      loading: {
        true: "cursor-wait opacity-90 pointer-events-none",
        false: "",
      },
      disabled: {
        true: "opacity-60 cursor-not-allowed pointer-events-none shadow-none active:transform-none active:shadow-none hover:transform-none hover:shadow-none",
        false: "",
      },
    },
    defaultVariants: {
      variant: "primary",
      size: "md",
      fullWidth: false,
      loading: false,
      disabled: false,
    },
  }
);

export type ButtonVariantProps = VariantProps<typeof buttonVariants>;
